### ISSUE TITLE
pu.Sorter fails for `largest_first` and `area_ratio`

### ISSUE THREAD

**Issue by avantyghem** [tjgalvin/pyink#10]
I am encountering the following error when trying to run `pu.Sorter` using either `area_ratio` or `largest_first`, since both use the line that fails: `order.extend(src_idx[src_order])`.

I'm not sure what to do about this. I've uploaded the relevant files to `vos:/cirada/continuum/VLASS_SOM/debug` in case you'd like to try recreating the error. My images all have `pixel_scale = 0.36*u.arcsec`.

Note that I've been able to run `pu.Sorter` successfully on a different sample.

```
In [239]: sorter = pu.Sorter(somset, annotation, mode="area_ratio")                                  
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-239-7fff26d47cf1> in <module>
----> 1 sorter = pu.Sorter(somset, annotation, mode="area_ratio")

~/Projects/pyink/pyink/collation.py in __init__(self, som_set, mode, *args, **kwargs)
    129             self.order = self._largest_order(*args, **kwargs)
    130         elif mode == "area_ratio":
--> 131             self.order = self._area_ratio(*args, **kwargs)
    132 
    133     def _ed_order(self) -> np.ndarray:

~/Projects/pyink/pyink/collation.py in _area_ratio(self, annotations, filter1, filter2, filter_includes, filter_excludes, sort_srcs, *args, **kwargs)
    238                 src_order = np.arange(src_idx.shape[0])
    239 
--> 240             order.extend(src_idx[src_order])
    241 
    242         return order

IndexError: too many indices for array
```

**Comment by avantyghem** [comment]
Possibly related, I've also encountered an error in the grouping stage. For the full version of what I'm doing see `collation.py` on VOSpace.

When running
```
actions = pu.LabelResolve(
    {"Follow up": pu.Action.PASS, "Radio": pu.Action.LINK, "Host": pu.Action.DATA_ATTACH,}
)

sorter = pu.Sorter(somset, annotation, mode="best_matching_first")

def src_fn(idx):
    return {"idx": idx * 2, "bmu": somset.mapping.bmu(idx)}

group = pu.Grouper(
    filters, annotation, actions, sorter, src_stats_fn=src_fn, progress=True
)
```
I obtain:

```
In [264]: group = pu.Grouper( 
     ...:     filters, annotation, actions, sorter, src_stats_fn=src_fn, progress=True 
     ...: )                                                                                          
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-264-3c12917df367> in <module>
      1 group = pu.Grouper(
----> 2     filters, annotation, actions, sorter, src_stats_fn=src_fn, progress=True
      3 )

~/Projects/pyink/pyink/collation.py in __init__(self, filters, annotations, label_resolve, sorter, src_stats_fn, progress)
    458         self.src_stats_fn = src_stats_fn
    459 
--> 460         self.graph: nx.MultiGraph = self._generate_graph()
    461 
    462     def _generate_graph(self) -> nx.MultiGraph:

~/Projects/pyink/pyink/collation.py in _generate_graph(self)
    472             self.sorter,
    473             src_stats_fn=self.src_stats_fn,
--> 474             progress=self.progress,
    475         )

~/Projects/pyink/pyink/collation.py in greedy_graph(filters, annotations, label_resolve, sorter, src_stats_fn, progress)
    386 
    387                 elif action == pu.Action.LINK:
--> 388                     node_link.extend(list(src_filter.coords.src_idx[mask]))
    389 
    390                 elif action == pu.Action.UNLINK:

IndexError: arrays used as indices must be of integer (or boolean) type```

**Comment by tjgalvin** [comment]
Thanks for reporting this. I will say that I am not entirely sure what is going on. I might need to look at the steps you have used a little more closely. The first error is a little odd. I am presuming that `src_idx[src_order]` is the troublesome component, and looking at the code `src_order` is defined just above it. It looks reasonable to me. Can you check to see how many sources each neuron has as their BMU? And are you keeping `sort_srcs` to be `True`? Would you be able to rerun but pass `sort_srcs=False` into `pu.Sorter`? 

My hunch is there might be a neuron with no sources... 

I think these calls could deal with some debug logging messages to help with these types of problems. If you happen to put in any yourself while sorting it out there is already a `logger` in the code there that can be used.

**Comment by avantyghem** [comment]
You're probably right that one (or more) of the neurons has no sources. I switched to a small region on the sky in order to keep my IR catalogue small, so I only have 420 radio components for a 10x10 SOM.

**Comment by tjgalvin** [comment]
Ok. Well that is good to know, but I think it should not happen in any case. I've just pushed a very simple change to hopefully fix this. Let me know if it does. This should fix the first error, and will probably do nothing for the second. One problem at a time.

**Comment by avantyghem** [comment]
The problem is actually when there's exactly one source in a neuron. It results in `array(99)` instead of `array([  2,   5,  18])`, so is an unsized object and doesn't cooperate with `src_idx[src_order]` (nor something like `len`, for that matter).

**Comment by avantyghem** [comment]
My proposed fix is to replace the final line of pu.Mapping.images_with_bmu to
`return np.array(np.squeeze(np.argwhere(mask)), ndmin=1)`
I've checked this against neurons with no matches (i.e. `mask` contains only `False`) and it works the same as before (as intended).
Looks like I don't have permissions to submit a PR.

**Comment by tjgalvin** [comment]
I've added the proposed fix as suggested, and added you as a contributor. You can also fork the project, create commits and submit a pull request from the forked repo to this one :)
