### ISSUE TITLE
Masking during preprocessing

### ISSUE THREAD

**Issue by avantyghem** [tjgalvin/pyink#2]
The `minmax` function in preprocessing.py is throwing the following error. The way the mask is currently handled (data = data[mask]) flattens the image to a 1D array, which is causing the problem. The mask can be added to a masked_array instead:
> data = np.ma.masked_array(data, mask=~mask)

Note the "~", since the mask in a masked_array follows a different convention than you are using (i.e. True means masked, whereas True in your functions indicate that the (inner) region is valid).

##################################################
IndexError                                Traceback (most recent call last)
<ipython-input-18-7744158b6a36> in <module>
----> 1 axes[1].imshow(process_ir(img_ir_ma))

<ipython-input-14-c1aff16f0314> in process_ir(img, weight)
      4     img = np.clip(img, 0.0001, 1e10)
      5     img = np.log10(img)
----> 6     img = pu.minmax(img, mask=mask)
      7     img = img * weight
      8     return img

~/Projects/pyink/pyink/preprocessing.py in minmax(data, mask)
     96         mask = np.ones_like(data, dtype=np.bool)
     97 
---> 98     scaled = (data - np.nanmin(data[mask])) / (
     99         np.nanmax(data[mask]) - np.nanmin(data[mask])
    100     )

**Comment by tjgalvin** [comment]
Looking at the code now and it seems like I have done something silly when bringing over functions from different locations. I think simply deleting the  `data = data[mask]` line completely would be fine. The mask region should only be used to calculating the scaling statistics, it should not be sub-setting the data at all.

**Comment by tjgalvin** [comment]
I've pushed it 3816199 that should not change the shape of the data, just uses the mask to compute the scaling region. 

Looking at the function it could probably be simplified a little - I don't like the full mask I generate when no user mask is defined...
