### ISSUE TITLE
Can't annotate properly

### ISSUE THREAD

**Issue by avantyghem** [tjgalvin/pyink#5]
When running `run_annotation_example.py` on a 5x5 SOM, the annotator is looping through the (0,0) neuron repeatedly. I'm not providing any optional arguments to the script.

Also, if I add a label it does not appear in the next iteration unless I add an extra label.

I'm running this on Ubuntu 18.04, if that matters.

**Comment by tjgalvin** [comment]
I have not run it on an ubuntu system, so there could very well be an issue at play here. 

I am not entirely sure how it is managing to loop over the first `(0,0)` neuron continuously. So when you press `n` the matplotlib window is destroyed and recreated on the same neuron? I can't seem to recreate this. 

The label bit is also an interesting case that I can reproduce. I think I have a feeling on why it is happening. 

I do need to add some instructions on how the necessary inputs to drive the tool. It has a few quirks that I would like to fix or improve.

**Comment by tjgalvin** [comment]
I think I 'fixed' the label issue with ea527a4. I was using an attribute of the `Annotation` class shared among all instances to record labels. That way if you went back to an earlier neuron any newly added labels would be present. This worked fine until pickling as these class attributes are not serialised without adding custom `__getstate__` and `__setstate__` methods. I hoped to avoid this, and seemed I may have messed up a little. I had to add a few checks (arguably hacks!) to let me update a single neuron after the fact as well. 

I'd be curious if there is a better way. I gave `dill` a go but it didn't seem to do the job. Perhaps something a little more sophisticated than a straight-forward `pickle`?

**Comment by avantyghem** [comment]
Okay I guess the main problem was actually that I just didn't know how to use the tool. There are no commands listed, so I was just closing the window instead of typing `n`.

**Comment by tjgalvin** [comment]
Ok, I will add some proper instructions shortly. Need to remember *other* people may want to use it :P

**Comment by tjgalvin** [comment]
I have added a few brief instructions to the code. When executing the `interactive_annotation` a help message will be printed to screen. These can also be accessed by typing either `help` or `commands` in the text box.
