### ISSUE TITLE
Preprocessing issue involving NaN

### ISSUE THREAD

**Issue by avantyghem** [tjgalvin/pyink#8]
I am running into a problem with the interaction between `reproject_interp` and `pu.rms_estimate`.

Specifically `reproject_interp` is giving me a row of NaN, which is not handled well by `pu.rms_estimate`. The reprojection is only shifting the centroid of my images by half a pixel in both directions, from (250.5, 250.5) to (250, 250)?

We may want to ensure `pu.rms_estimate` ignores NaNs. This would help in cases where a bright source has already been masked.

**Comment by tjgalvin** [comment]
I've added an option to `rms_estimate` to remove any NaNs from the data when estimating the RMS, which I set to true by default. See if 64f5bd8 helps.

**Comment by tjgalvin** [comment]
Actually, silly me. I was masking out all good values of `data` in the previous commit. This should be corrected now in 4a20fa9.

I think that we should spend some time to get the test cases written to ensure things behave like we expect. See #3.
